name: Lint & Test (ESLint & Jest)

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install npm modules
        run: npm install

      - name: Run eslint
        run: npm run lint

      - name: Run jest
        run: npm run test
