name: Test (ESLint)

on: [push, pull_request]

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install npm modules
        run: npm install

      - name: Run jest
        run: npm run jest

